package printer

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// tiny1x1PNGBase64 is a real 1x1 transparent PNG, base64-encoded, used to
// exercise the thumbnail decode path without shipping a binary fixture.
const tiny1x1PNGBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="

var pngMagic = []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}

// orcaHeader is a representative sample of an OrcaSlicer-style header
// (generator line, estimate, filament/layer/temperature comments and a
// base64 PNG thumbnail block), plus a small body and an OrcaSlicer-style
// footer.
func orcaSampleLines() []string {
	return []string{
		"; generated by OrcaSlicer 2.1.0 on 2024-01-01 at 12:00:00",
		"; estimated printing time (normal mode) = 2h 1m 0s",
		"; filament used [g] = 41.20",
		"; filament used [mm] = 13800.00",
		"; layer_height = 0.2",
		"; nozzle_diameter = 0.4",
		"; nozzle_temperature = 215",
		"; bed_temperature = 60",
		"; thumbnail begin 32x32 " + strconv.Itoa(len(tiny1x1PNGBase64)),
		"; " + tiny1x1PNGBase64,
		"; thumbnail end",
		"G28",
		"G1 X0 Y0 F3000",
		"M104 S210", // must NOT override the 215 already parsed from comments
		"M140 S55",  // must NOT override the 60 already parsed from comments
		"G1 X10 Y10 E1",
		"; filament used [g] = 41.20 (footer restated, common in Prusa/Orca)",
	}
}

func TestMetaParserOrcaHeaderFooterAndThumbnail(t *testing.T) {
	p := &metaParser{}
	for _, line := range orcaSampleLines() {
		p.feed(line)
	}
	meta, png := p.result()

	if meta.Slicer != "OrcaSlicer 2.1.0" {
		t.Errorf("Slicer = %q", meta.Slicer)
	}
	if meta.EstSec != 2*3600+1*60 {
		t.Errorf("EstSec = %d, want %d", meta.EstSec, 2*3600+60)
	}
	if meta.FilamentG != 41.20 {
		t.Errorf("FilamentG = %v", meta.FilamentG)
	}
	if meta.FilamentMm != 13800.00 {
		t.Errorf("FilamentMm = %v", meta.FilamentMm)
	}
	if meta.LayerHeight != 0.2 {
		t.Errorf("LayerHeight = %v", meta.LayerHeight)
	}
	if meta.Nozzle != 0.4 {
		t.Errorf("Nozzle = %v", meta.Nozzle)
	}
	if meta.HotendC != 215 {
		t.Errorf("HotendC = %v, want 215 (comment must win over the M104 body fallback)", meta.HotendC)
	}
	if meta.BedC != 60 {
		t.Errorf("BedC = %v, want 60 (comment must win over the M140 body fallback)", meta.BedC)
	}
	if !meta.Thumb {
		t.Fatal("Thumb = false, want true")
	}
	if len(png) < 8 || !bytes.Equal(png[:8], pngMagic) {
		t.Fatalf("decoded thumbnail does not start with the PNG magic: % x", png[:min(len(png), 8)])
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// TestMetaParserCommandFallback: without any header comments, the first
// M104/M140 in the body sets the temperatures.
func TestMetaParserCommandFallback(t *testing.T) {
	p := &metaParser{}
	for _, line := range []string{"G28", "M104 S200", "M140 S60", "M104 S210"} {
		p.feed(line)
	}
	meta, _ := p.result()
	if meta.HotendC != 200 || meta.BedC != 60 {
		t.Fatalf("meta = %+v, want first M104/M140 only", meta)
	}
}

// TestMetaParserOversizeThumbnailDropped: a thumbnail bigger than 300x300
// must not be kept.
func TestMetaParserOversizeThumbnailDropped(t *testing.T) {
	p := &metaParser{}
	for _, line := range []string{
		"; thumbnail begin 400x400 4",
		"; QUJD",
		"; thumbnail end",
	} {
		p.feed(line)
	}
	meta, png := p.result()
	if meta.Thumb || png != nil {
		t.Fatalf("oversize thumbnail was kept: meta=%+v png_len=%d", meta, len(png))
	}
}

// TestMetaParserKeepsLargestThumbnail: of several thumbnail blocks (as Orca
// emits: several sizes for different preview uses), the largest one within
// the cap is kept.
func TestMetaParserKeepsLargestThumbnail(t *testing.T) {
	p := &metaParser{}
	small := "; " + tiny1x1PNGBase64
	for _, line := range []string{
		"; thumbnail begin 16x16 " + strconv.Itoa(len(tiny1x1PNGBase64)),
		small,
		"; thumbnail end",
		"; thumbnail begin 200x200 " + strconv.Itoa(len(tiny1x1PNGBase64)),
		small,
		"; thumbnail end",
	} {
		p.feed(line)
	}
	if p.bestThumb == nil || p.bestThumb.w != 200 {
		t.Fatalf("bestThumb = %+v, want the 200x200 block", p.bestThumb)
	}
}

func TestParseSlicerDuration(t *testing.T) {
	cases := map[string]int{
		"2h 1m 0s": 2*3600 + 60,
		"5m 3s":    5*60 + 3,
		"45s":      45,
		"":         0,
	}
	for in, want := range cases {
		got, ok := parseSlicerDuration(in)
		if in == "" {
			if ok {
				t.Errorf("parseSlicerDuration(%q) ok=true, want false", in)
			}
			continue
		}
		if !ok || got != want {
			t.Errorf("parseSlicerDuration(%q) = %d, %v; want %d", in, got, ok, want)
		}
	}
}

func TestMetaStoreSaveGetDeleteAndEviction(t *testing.T) {
	dir := t.TempDir()
	ms := NewMetaStore(dir)

	meta := SDMeta{EstSec: 100, Slicer: "Test"}
	if err := ms.Save("A.GCO", meta, []byte("not a real png but bytes")); err != nil {
		t.Fatalf("Save: %v", err)
	}
	got := ms.Get("A.GCO")
	if got == nil || got.EstSec != 100 || got.Slicer != "Test" {
		t.Fatalf("Get = %+v", got)
	}
	if p, ok := ms.ThumbPath("A.GCO"); !ok || p == "" {
		t.Fatalf("ThumbPath ok=%v p=%q", ok, p)
	}

	ms.Delete("A.GCO")
	if ms.Get("A.GCO") != nil {
		t.Fatal("Get after Delete: expected nil")
	}
	if _, ok := ms.ThumbPath("A.GCO"); ok {
		t.Fatal("ThumbPath after Delete: expected false")
	}

	// Eviction: fill past the cap with several files, then confirm the
	// total on disk stays bounded and the earliest write got evicted.
	big := bytes.Repeat([]byte("x"), 200<<10) // 200KiB per thumbnail
	for i := 0; i < 8; i++ {                  // 8 * 200KiB > metaCapBytes (1MB)
		name := filepath.Join("F" + strconv.Itoa(i) + ".GCO")
		if err := ms.Save(name, SDMeta{}, big); err != nil {
			t.Fatalf("Save %d: %v", i, err)
		}
	}
	var total int64
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		info, err := e.Info()
		if err != nil {
			continue
		}
		total += info.Size()
	}
	if total > metaCapBytes {
		t.Fatalf("total on disk = %d, want <= %d after eviction", total, metaCapBytes)
	}
	if ms.Get("F0.GCO") != nil {
		if _, ok := ms.ThumbPath("F0.GCO"); ok {
			t.Fatal("earliest file should have been evicted")
		}
	}
}

func TestSDFileMetaJSONOmitsEmptyFields(t *testing.T) {
	// A zero-value SDMeta must marshal to "{}" (every field omitempty), so
	// SDFile.Meta only ever adds bytes to the response when there's
	// something to say.
	data, err := json.Marshal(SDMeta{})
	if err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(string(data)) != "{}" {
		t.Fatalf("empty SDMeta marshaled to %q, want {}", data)
	}
}
